[project]
name = "genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.1.0",
    "bs4>=0.0.2",
    "chromadb>=1.5.1",
    "ddgs>=9.11.2",
    "duckduckgo-search>=8.1.1",
    "faiss-cpu>=1.13.2",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "langchain>=1.2.10",
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.1",
    "langchain-community>=0.4.1",
    "langchain-experimental>=0.4.1",
    "langchain-google-genai>=4.2.1",
    "langchain-mistralai>=1.1.1",
    "langchain-openrouter>=0.0.2",
    "langchain-text-splitters>=1.1.1",
    "langchain-unstructured>=1.0.1",
    "pdfminer-six>=20260107",
    "pillow>=12.1.1",
    "pydantic[email]>=2.12.5",
    "pypdf>=6.7.5",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.2",
    "streamlit>=1.54.0",
    "tavily>=1.1.0",
    "wikipedia>=1.4.0",
    "youtube-transcript-api>=1.2.4",
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 200
target-version = "py312"
select = ["E", "F", "I"]
